<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/control.proto

namespace Longbridge\Control\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>longbridge.control.v1.AuthResponse</code>
 */
class AuthResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string session_id = 1;</code>
     */
    protected $session_id = '';
    /**
     * Generated from protobuf field <code>int64 expires = 2;</code>
     */
    protected $expires = 0;
    /**
     * Generated from protobuf field <code>uint32 limit = 3;</code>
     */
    protected $limit = 0;
    /**
     * Generated from protobuf field <code>uint32 online = 4;</code>
     */
    protected $online = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $session_id
     *     @type int|string $expires
     *     @type int $limit
     *     @type int $online
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Control::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string session_id = 1;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Generated from protobuf field <code>string session_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expires = 2;</code>
     * @return int|string
     */
    public function getExpires()
    {
        return $this->expires;
    }

    /**
     * Generated from protobuf field <code>int64 expires = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpires($var)
    {
        GPBUtil::checkInt64($var);
        $this->expires = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 limit = 3;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>uint32 limit = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 online = 4;</code>
     * @return int
     */
    public function getOnline()
    {
        return $this->online;
    }

    /**
     * Generated from protobuf field <code>uint32 online = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOnline($var)
    {
        GPBUtil::checkUint32($var);
        $this->online = $var;

        return $this;
    }

}

