<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/control.proto

namespace Longbridge\Control\V1;

if (false) {
    /**
     * This class is deprecated. Use Longbridge\Control\V1\Close\Code instead.
     * @deprecated
     */
    class Close_Code {}
}
class_exists(Close\Code::class);
@trigger_error('Longbridge\Control\V1\Close_Code is deprecated and will be removed in the next major release. Use Longbridge\Control\V1\Close\Code instead', E_USER_DEPRECATED);

