<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/control.proto

namespace Longbridge\Control\V1;

use UnexpectedValueException;

/**
 * control command, see document: https://open.longbridge.com/docs/socket/control-command
 *
 * Protobuf type <code>longbridge.control.v1.Command</code>
 */
class Command
{
    /**
     * Generated from protobuf enum <code>CMD_CLOSE = 0;</code>
     */
    const CMD_CLOSE = 0;
    /**
     * Generated from protobuf enum <code>CMD_HEARTBEAT = 1;</code>
     */
    const CMD_HEARTBEAT = 1;
    /**
     * Generated from protobuf enum <code>CMD_AUTH = 2;</code>
     */
    const CMD_AUTH = 2;
    /**
     * Generated from protobuf enum <code>CMD_RECONNECT = 3;</code>
     */
    const CMD_RECONNECT = 3;

    private static $valueToName = [
        self::CMD_CLOSE => 'CMD_CLOSE',
        self::CMD_HEARTBEAT => 'CMD_HEARTBEAT',
        self::CMD_AUTH => 'CMD_AUTH',
        self::CMD_RECONNECT => 'CMD_RECONNECT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

