<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/control.proto

namespace Longbridge\Control\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>longbridge.control.v1.Heartbeat</code>
 */
class Heartbeat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>optional int32 heartbeat_id = 2;</code>
     */
    protected $heartbeat_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $timestamp
     *     @type int $heartbeat_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Control::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 heartbeat_id = 2;</code>
     * @return int
     */
    public function getHeartbeatId()
    {
        return isset($this->heartbeat_id) ? $this->heartbeat_id : 0;
    }

    public function hasHeartbeatId()
    {
        return isset($this->heartbeat_id);
    }

    public function clearHeartbeatId()
    {
        unset($this->heartbeat_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 heartbeat_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setHeartbeatId($var)
    {
        GPBUtil::checkInt32($var);
        $this->heartbeat_id = $var;

        return $this;
    }

}

